server:
  port: 8888

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Casper-Config-Server
  web:
    resources:
      add-mappings: false
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT prop_key, prop_value FROM tbl_environment_configuration WHERE application = ? AND profile = ? AND label = ?
          order: 1
        encrypt:
          enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

encrypt:
  key: ${ENCRYPT_KEY}
  salt: ${ENCRYPT_SALT}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  issuer: casper-config-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud: INFO
    org.springframework.jdbc: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE